# this is a sample config file. 
# copy this file to "config.yaml" to use with the server
server:
  # port the server runs on
  port: 8080
github:
  # repository that contains teams.json and questions.json
  repository: health-check-server
  # owner of the repository
  username: carl
  # token with access to the repository. needs "repo" permission
  token: carlsCoolPersonalAccessToken