services:
  server:
    image: health-check-server:latest
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
      image: postgres:14
      environment:
        - POSTGRES_DB=healthcheck
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=crazytownbananapants
      command: postgres -c max_connections=1500
      ports:
        - 5432:5432
      volumes:
        - postgres:/var/lib/postgresql/data

volumes:
  postgres:
