services:
  db:
      image: postgres:14
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=crazytownbananapants
      command: postgres -c max_connections=1500
      ports:
        - 5432:5432
      volumes:
        - postgres:/var/lib/postgresql/data

volumes:
  postgres:
